import {adviceFor,validateReading} from './safety.mjs';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const config=window.PULSO_CONFIG||{}, configured=!!(config.supabaseUrl&&config.supabaseKey);
let records=[], session=null, editId=null, deleteId=null, signup=false, range='7', loadSequence=0;
const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=d=>new Intl.DateTimeFormat('pt-BR',{day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(d));
const dateKey=d=>{const x=new Date(d);return `${x.getFullYear()}-${String(x.getMonth()+1).padStart(2,'0')}-${String(x.getDate()).padStart(2,'0')}`};
function localDatetime(d=new Date()){return `${dateKey(d)}T${String(d.getHours()).padStart(2,'0')}:${String(d.getMinutes()).padStart(2,'0')}`}
const periodFor=d=>d.getHours()<12?'Manhã':d.getHours()<18?'Tarde':'Noite';
let toastTimer;function toast(message){$('#toast').textContent=message;$('#toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').hidden=true,4500)}
function banner(message){$('#connection-banner').hidden=!message;$('#connection-banner').textContent=message||''}
function setView(view){$$('.view').forEach(el=>el.hidden=el.id!==`view-${view}`);$$('[data-view]').forEach(el=>el.classList.toggle('active',el.dataset.view===view));location.hash=view;window.scrollTo({top:0,behavior:'smooth'})}
function saveSession(s){session=s;if(s)sessionStorage.setItem('pulso-session',JSON.stringify(s));else sessionStorage.removeItem('pulso-session');renderAccount()}
async function request(path,{method='GET',body,auth=false,retry=true}={}){
  if(!configured)throw Error('A configuração do armazenamento ainda está pendente. Não há registros sendo salvos.');
  if(auth&&!session)throw Error('Entre na sua conta para acessar os registros.');
  if(auth&&retry&&session.expires_at<Date.now()/1000+45)await refreshSession();
  const headers={'apikey':config.supabaseKey,'Content-Type':'application/json'};
  if(auth)headers.Authorization=`Bearer ${session.access_token}`;
  if(path.startsWith('/rest/'))headers.Prefer='return=representation';
  let response;
  try{response=await fetch(config.supabaseUrl+path,{method,headers,body:body===undefined?undefined:JSON.stringify(body),signal:AbortSignal.timeout(15000)})}catch{throw Error('Não foi possível conectar. Confira sua internet e tente novamente. Nenhum salvamento foi confirmado.')}
  const data=response.status===204?null:await response.json().catch(()=>null);
  if(response.status===401&&auth&&retry){await refreshSession();return request(path,{method,body,auth,retry:false})}
  if(!response.ok){const raw=data?.msg||data?.message||data?.error_description||'';if(/Invalid login/.test(raw))throw Error('E-mail ou senha incorretos.');if(/Email not confirmed/.test(raw))throw Error('Confirme seu e-mail antes de entrar.');if(/rate limit/i.test(raw))throw Error('Muitas tentativas. Aguarde alguns minutos e tente novamente.');if(/email.*not.*authorized/i.test(raw))throw Error('O envio de confirmação de e-mail precisa ser configurado pelo responsável pelo app.');throw Error(path.startsWith('/rest/')?'Não foi possível concluir a operação. Tente novamente; se persistir, avise o responsável pelo app.':raw||'Não foi possível entrar. Tente novamente.')}
  return data;
}
async function refreshSession(){if(!session?.refresh_token)throw Error('Entre novamente para continuar.');try{const data=await request('/auth/v1/token?grant_type=refresh_token',{method:'POST',body:{refresh_token:session.refresh_token},retry:false});saveSession(data)}catch(e){saveSession(null);records=[];render();banner('Sua sessão expirou. Entre novamente para acessar seus registros.');throw e}}
function renderAccount(){const email=session?.user?.email;$('#account-name').textContent=email||'Seu espaço particular';$('#account-status').textContent=session?'Conta conectada':'Entre para sincronizar';$('#session-button').textContent=session?'Sair da conta':'Entrar na conta';$('#account-detail').textContent=session?`Conectada como ${email}. Seus registros são sincronizados com esta conta.`:'Entre ou crie uma conta para salvar seus registros com segurança.';$('#manage-account').textContent=session?'Sair da conta':'Entrar / criar conta';$('#sync-now').hidden=!session}
async function loadRecords(){if(!session)return;const sequence=++loadSequence;banner('Atualizando seus registros…');try{let data=[],offset=0;while(true){const chunk=await request(`/rest/v1/pulso_readings?select=*&order=measured_at.desc&limit=500&offset=${offset}`,{auth:true});if(sequence!==loadSequence)return;data.push(...chunk);if(chunk.length<500)break;offset+=500}records=data;banner('');render();$('#account-status').textContent='Sincronizado agora'}catch(e){if(sequence!==loadSequence)return;banner(e.message);$('#account-status').textContent='Não foi possível atualizar'}}
function subset(){if(range==='all')return records;const since=new Date();since.setDate(since.getDate()-Number(range)+1);since.setHours(0,0,0,0);return records.filter(r=>new Date(r.measured_at)>=since)}
function filtered(){const start=$('#filter-start').value,end=$('#filter-end').value,period=$('#filter-period').value;return records.filter(r=>{const day=dateKey(r.measured_at);return(!start||day>=start)&&(!end||day<=end)&&(period==='all'||r.period===period)})}
function row(r,history=false){const a=adviceFor(r);return `<div class="${history?'history-item':''}"><div class="reading-row"><span class="reading-mark" aria-hidden="true">${r.period==='Manhã'?'☀':r.period==='Tarde'?'◷':'☾'}</span><div class="reading-info"><strong>${escape(r.period)}</strong><small>${fmt(r.measured_at)}</small>${history?`<span class="status-chip ${a.level==='calm'?'':a.level}">${escape(a.label)}</span>`:''}</div><div class="reading-values"><strong>${r.systolic} / ${r.diastolic}</strong><small>mmHg${r.pulse?` · ${r.pulse} bpm`:''}</small></div>${history?`<div class="reading-actions"><button data-edit="${r.id}" aria-label="Editar medição de ${fmt(r.measured_at)}">Editar</button><button data-delete="${r.id}" aria-label="Excluir medição de ${fmt(r.measured_at)}">Excluir</button></div>`:''}</div>${history&&(r.symptoms?.length||r.notes)?`<div class="notes">${r.symptoms?.length?`<strong>Sintomas:</strong> ${escape(r.symptoms.join(', '))}<br>`:''}${escape(r.notes)}</div>`:''}</div>`}
function empty(title='Nenhuma medição ainda',copy='Registre sua pressão para começar seu histórico.'){return `<div class="empty"><strong>${title}</strong>${copy}</div>`}
function render(){
  const last=records[0],recent=subset(),today=records.filter(r=>dateKey(r.measured_at)===dateKey(new Date()));
  $('#last-sys').textContent=last?.systolic||'—';$('#last-dia').textContent=last?.diastolic||'—';$('#last-period').textContent=last?.period||'Sem registros';$('#last-time').textContent=last?fmt(last.measured_at):'—';$('#last-status').textContent=last?adviceFor(last).label:'Comece pelo seu primeiro registro';
  const days=new Set(today.map(r=>r.period));$('#day-count').textContent=`${days.size} de 3 períodos`;
  $('#day-periods').innerHTML=['Manhã','Tarde','Noite'].map((p,i)=>`<button class="period-card ${days.has(p)?'complete':''}" data-new-period="${p}"><span class="period-icon" aria-hidden="true">${['☀','◷','☾'][i]}</span><strong>${p}</strong><small>${days.has(p)?'✓ Registrado':'Registrar'}</small></button>`).join('');
  const avg=key=>Math.round(recent.reduce((sum,r)=>sum+r[key],0)/recent.length);$('#average').textContent=recent.length?`${avg('systolic')} / ${avg('diastolic')}`:'— / —';const pulses=recent.filter(r=>r.pulse!==null);$('#average-pulse').innerHTML=`${pulses.length?Math.round(pulses.reduce((s,r)=>s+r.pulse,0)/pulses.length):'—'} <small>bpm</small>`;$('#total').textContent=recent.length;$('#period-caption').textContent=range==='all'?'Todo o histórico':`Últimos ${range} dias`;
  $('#recent-list').innerHTML=records.length?records.slice(0,3).map(r=>row(r)).join(''):empty();
  if(last){const a=adviceFor(last);$('#guidance-title').textContent=a.title;$('#guidance-copy').textContent=`Na medição de ${fmt(last.measured_at)}: ${a.text}`}else{$('#guidance-title').textContent='Antes de medir';$('#guidance-copy').textContent='Sente-se em silêncio por 5 minutos, com as costas apoiadas, pés no chão e braço na altura do coração.'}
  renderChart(recent);renderHistory();renderAccount();
}
function renderHistory(){const selected=filtered();$('#history-count').textContent=`${selected.length} ${selected.length===1?'registro':'registros'}`;$('#history-list').innerHTML=selected.length?selected.map(r=>row(r,true)).join(''):empty('Nenhum registro neste intervalo','Ajuste os filtros ou adicione uma medição.')}
function renderChart(data){if(!data.length){$('#chart').innerHTML=empty('Seu histórico começa aqui','As medições aparecerão neste gráfico após o primeiro registro.');return}const points=[...data].reverse(),w=Math.max(300,$('#chart').clientWidth),h=230,left=45,right=20,top=18,bottom=35,min=Math.max(0,Math.floor(Math.min(...points.map(r=>r.diastolic))/20)*20-20),max=Math.ceil(Math.max(...points.map(r=>r.systolic))/20)*20+20;const first=new Date(points[0].measured_at).getTime(),last=new Date(points.at(-1).measured_at).getTime();const x=r=>points.length===1?w/2:left+(new Date(r.measured_at).getTime()-first)/Math.max(1,last-first)*(w-left-right),y=v=>top+(max-v)/(max-min)*(h-top-bottom);let grid='';for(let i=0;i<=4;i++){const value=Math.round(min+(max-min)*i/4);grid+=`<line x1="${left}" x2="${w-right}" y1="${y(value)}" y2="${y(value)}" stroke="#e7eff1" stroke-dasharray="3 5"/><text x="0" y="${y(value)+4}" fill="#769098" font-size="12">${value}</text>`}const lines=['systolic','diastolic'].map((key,j)=>`<polyline points="${points.map(r=>`${x(r)},${y(r[key])}`).join(' ')}" fill="none" stroke="${j?'#7caab7':'#147384'}" stroke-width="${j?2:2.8}" stroke-linecap="round" stroke-linejoin="round"/>${points.map(r=>`<circle cx="${x(r)}" cy="${y(r[key])}" r="3.7" fill="${j?'#7caab7':'#147384'}" stroke="#fff" stroke-width="1.5"><title>${fmt(r.measured_at)} · ${r[key]} mmHg</title></circle>`).join('')}`).join('');const label=r=>new Date(r.measured_at).toLocaleDateString('pt-BR',{day:'2-digit',month:'2-digit'});$('#chart').innerHTML=`<svg role="img" aria-label="${points.length} medições de pressão arterial no período selecionado" viewBox="0 0 ${w} ${h}" preserveAspectRatio="none">${grid}${lines}<text x="${left}" y="${h-4}" fill="#769098" font-size="12">${label(points[0])}</text>${points.length>1?`<text x="${w-right}" y="${h-4}" text-anchor="end" fill="#769098" font-size="12">${label(points.at(-1))}</text>`:''}</svg>`}
function openAuth(){signup=false;$('#auth-form').reset();$('#auth-error').textContent='';updateAuthLabels();$('#auth-dialog').showModal()}
function updateAuthLabels(){$('#auth-title').textContent=signup?'Crie seu diário particular':'Entre no seu diário';$('#auth-submit').textContent=signup?'Criar conta':'Entrar';$('#toggle-auth').textContent=signup?'Já tenho conta. Entrar':'Primeiro acesso? Criar conta';$('#auth-form').elements.password.autocomplete=signup?'new-password':'current-password'}
function openReading(id=null,period=null){if(!session){toast('Entre na sua conta para registrar e sincronizar.');openAuth();return}editId=id;const f=$('#reading-form');f.reset();$('#reading-error').textContent='';$('#reading-title').textContent=id?'Editar medição':'Registrar pressão';const r=id?records.find(r=>r.id===id):null;if(r){for(const key of ['systolic','diastolic','pulse','period','notes'])f.elements[key].value=r[key]??'';f.elements.measured_at.value=localDatetime(new Date(r.measured_at));$$('[name="symptom"]').forEach(el=>el.checked=r.symptoms.includes(el.value))}else{f.elements.measured_at.value=localDatetime();f.elements.period.value=period||periodFor(new Date())}updateLiveAdvice();$('#reading-dialog').showModal()}
function formReading(){const f=$('#reading-form'),v=new FormData(f),date=new Date(v.get('measured_at'));return {systolic:Number(v.get('systolic')),diastolic:Number(v.get('diastolic')),pulse:v.get('pulse')?Number(v.get('pulse')):null,period:v.get('period'),measured_at:Number.isNaN(date.getTime())?'':date.toISOString(),symptoms:v.getAll('symptom'),notes:String(v.get('notes')||'').trim()}}
function updateLiveAdvice(){const r=formReading();const a=adviceFor(r);const el=$('#live-advice');el.className=`advice ${a.level==='calm'?'':a.level}`;el.innerHTML=`<strong>${escape(a.title)}</strong><br>${escape(a.text)}${a.emergency?'<a href="tel:192">Ligar para o SAMU · 192</a>':''}`}
async function signout(){try{await request('/auth/v1/logout',{method:'POST',auth:true})}catch{}++loadSequence;saveSession(null);records=[];render();banner('');toast('Você saiu da conta.');}
document.addEventListener('click',e=>{const nav=e.target.closest('[data-view]');if(nav)setView(nav.dataset.view);if(e.target.closest('.new-reading'))openReading();const p=e.target.closest('[data-new-period]');if(p)openReading(null,p.dataset.newPeriod);if(e.target.closest('.close-dialog'))e.target.closest('dialog').close();const edit=e.target.closest('[data-edit]');if(edit)openReading(edit.dataset.edit);const del=e.target.closest('[data-delete]');if(del){deleteId=del.dataset.delete;$('#delete-error').textContent='';$('#confirm-dialog').showModal()}if(e.target.closest('.report-action'))printReport()});
$('#session-button').onclick=()=>session?signout():openAuth();$('#manage-account').onclick=()=>session?signout():openAuth();$('#sync-now').onclick=()=>loadRecords();$('#toggle-auth').onclick=()=>{signup=!signup;$('#auth-error').textContent='';updateAuthLabels()};
$('#auth-form').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget,button=$('#auth-submit');button.disabled=true;$('#auth-error').textContent='';try{const email=f.elements.email.value.trim(),password=f.elements.password.value;const data=await request(signup?'/auth/v1/signup':'/auth/v1/token?grant_type=password',{method:'POST',body:{email,password}});if(data?.access_token){saveSession(data);f.reset();$('#auth-dialog').close();await loadRecords();toast(signup?'Conta criada. Seu diário está pronto.':'Você entrou na sua conta.')}else{$('#auth-error').textContent='Confira seu e-mail para confirmar o cadastro. Depois, volte ao app e entre com sua senha.';signup=false;updateAuthLabels()}}catch(err){$('#auth-error').textContent=err.message}finally{button.disabled=false}};
$('#reading-form').addEventListener('input',updateLiveAdvice);
$('#reading-form').onsubmit=async e=>{e.preventDefault();const button=$('#save-reading');$('#reading-error').textContent='';button.disabled=true;try{const r=formReading();validateReading(r);const body=editId?r:{...r,id:crypto.randomUUID(),user_id:session.user.id};const path=editId?`/rest/v1/pulso_readings?id=eq.${encodeURIComponent(editId)}`:'/rest/v1/pulso_readings';const saved=await request(path,{method:editId?'PATCH':'POST',body,auth:true});if(!saved?.length)throw Error('Nenhum registro foi confirmado. Atualize e tente novamente.');++loadSequence;records=records.filter(x=>x.id!==saved[0].id);records.push(saved[0]);records.sort((a,b)=>new Date(b.measured_at)-new Date(a.measured_at));render();banner('');$('#reading-dialog').close();toast(editId?'Medição atualizada.':'Registro salvo e sincronizado.');editId=null}catch(err){$('#reading-error').textContent=err.message}finally{button.disabled=false}};
$('#cancel-delete').onclick=()=>$('#confirm-dialog').close();$('#confirm-delete').onclick=async()=>{const b=$('#confirm-delete');b.disabled=true;try{const result=await request(`/rest/v1/pulso_readings?id=eq.${encodeURIComponent(deleteId)}`,{method:'DELETE',auth:true});if(!result?.length)throw Error('A exclusão não foi confirmada. Atualize e tente novamente.');++loadSequence;records=records.filter(r=>r.id!==deleteId);render();$('#confirm-dialog').close();toast('Registro excluído.')}catch(e){$('#delete-error').textContent=e.message}finally{b.disabled=false}};
$('#chart-range').onchange=e=>{range=e.target.value;render()};['filter-start','filter-end','filter-period'].forEach(id=>$('#'+id).onchange=renderHistory);$('#clear-filters').onclick=()=>{$('#filter-start').value='';$('#filter-end').value='';$('#filter-period').value='all';renderHistory()};
function csvCell(value){let s=String(value??'');if(/^[=+\-@\t\r]/.test(s))s="'"+s;return '"'+s.replace(/"/g,'""')+'"'}
$('#export-csv').onclick=()=>{const data=filtered();if(!data.length){toast('Nenhum registro no intervalo selecionado.');return}const rows=[['Data e hora','Período','Sistólica (mmHg)','Diastólica (mmHg)','Pulso (bpm)','Sintomas','Observações'],...data.map(r=>[fmt(r.measured_at),r.period,r.systolic,r.diastolic,r.pulse,r.symptoms.join(', '),r.notes])];const blob=new Blob(['\ufeff'+rows.map(r=>r.map(csvCell).join(';')).join('\r\n')],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`pulso-registros-${dateKey(new Date())}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
function printReport(){const data=filtered();if(!data.length){toast('Adicione uma medição antes de gerar o relatório.');return}setView('historico');$$('.report-header,.report-only').forEach(el=>el.remove());const header=document.createElement('div');header.className='report-header';header.innerHTML=`<h1>Pulso · Diário de pressão arterial</h1><p>Conta: ${escape(session?.user?.email||'')}<br>Gerado em ${fmt(new Date())} · ${data.length} medições<br>Intervalo: ${$('#filter-start').value||'início do histórico'} a ${$('#filter-end').value||'hoje'} · Período: ${escape($('#filter-period').value==='all'?'todos':$('#filter-period').value)}</p>`;$('#view-historico').prepend(header);const foot=document.createElement('p');foot.className='report-only';foot.textContent='Valores informados pela usuária, não verificados pelo app. Este diário não estabelece diagnóstico e não substitui a avaliação médica. Os sintomas registrados se referem ao momento de cada medição. A média não descarta episódios de pressão muito elevada.';$('#view-historico').append(foot);window.print()}
$('#today-date').textContent=new Intl.DateTimeFormat('pt-BR',{weekday:'long',day:'numeric',month:'long'}).format(new Date());
try{session=JSON.parse(sessionStorage.getItem('pulso-session')||'null')}catch{sessionStorage.removeItem('pulso-session')}
setView(['inicio','historico','cuidados','conta'].includes(location.hash.slice(1))?location.hash.slice(1):'inicio');render();
if(!configured)banner('Prévia do aplicativo. A conexão com o banco e a publicação ainda precisam ser concluídas. Nenhuma informação de saúde será salva nesta prévia.');else if(session)loadRecords();else banner('Entre ou crie uma conta para começar. Seus registros ficarão privados e disponíveis nos aparelhos em que você entrar.');
document.addEventListener('visibilitychange',()=>{if(!document.hidden&&session)loadRecords()});
