import {adviceFor,validateReading} from './safety.mjs';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const config=window.PULSO_CONFIG||{}, configured=!!(config.supabaseUrl&&config.supabaseKey);
let records=[], access=null, editId=null, deleteId=null, range='7', loadSequence=0, diaryReady=Promise.resolve();
const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=d=>new Intl.DateTimeFormat('pt-BR',{day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(d));
const dateKey=d=>{const x=new Date(d);return `${x.getFullYear()}-${String(x.getMonth()+1).padStart(2,'0')}-${String(x.getDate()).padStart(2,'0')}`};
function localDatetime(d=new Date()){return `${dateKey(d)}T${String(d.getHours()).padStart(2,'0')}:${String(d.getMinutes()).padStart(2,'0')}`}
const periodFor=d=>d.getHours()<12?'Manhã':d.getHours()<18?'Tarde':'Noite';
let toastTimer;function toast(message){$('#toast').textContent=message;$('#toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').hidden=true,4500)}
function banner(message){$('#connection-banner').hidden=!message;$('#connection-banner').textContent=message||''}
function setView(view){if($('#navigation-menu').open)$('#navigation-menu').close();$$('.view').forEach(el=>el.hidden=el.id!==`view-${view}`);$$('[data-view]').forEach(el=>el.classList.toggle('active',el.dataset.view===view));location.hash=view;window.scrollTo({top:0,behavior:'smooth'})}
async function request(path='',{method='GET',body}={}){
 if(!configured)throw Error('A conexão com o diário ainda precisa ser configurada.');
 await diaryReady;if(!access)throw Error('Não consegui preparar este aparelho. Atualize a página.');
 let response;try{response=await fetch(config.supabaseUrl+'/functions/v1/pulso-diary'+path,{method,headers:{apikey:config.supabaseKey,'Content-Type':'application/json','x-pulso-access':access},body:body===undefined?undefined:JSON.stringify(body),signal:AbortSignal.timeout(15000)})}catch{throw Error('Não consegui conectar. Confira a internet e tente de novo. Nenhum salvamento foi confirmado.')}
 const data=await response.json().catch(()=>null);if(!response.ok)throw Error(data?.message||'Não consegui concluir. Tente novamente.');return data;
}
function renderAccount(){$('#account-name').textContent='Seu cantinho pessoal';$('#account-status').textContent=access?'Diário deste aparelho':'Preparando seu diário';$('#account-detail').textContent='Preencha os números na tela inicial. Este navegador lembra seu acesso. Vincule outros aparelhos abaixo para manter o mesmo diário sincronizado.';}
async function loadRecords(silent=false){if(!access)return;const sequence=++loadSequence;if(!silent)banner('Organizando seu diário…');try{const data=await request();if(sequence!==loadSequence)return;records=data;banner('');render();$('#account-status').textContent='Tudo sincronizado 💜'}catch(e){if(sequence===loadSequence){banner(e.message);$('#account-status').textContent='Sem sincronização — confira sua conexão'}}}
function subset(){if(range==='all')return records;const since=new Date();since.setDate(since.getDate()-Number(range)+1);since.setHours(0,0,0,0);return records.filter(r=>new Date(r.measured_at)>=since)}
function filtered(){const start=$('#filter-start').value,end=$('#filter-end').value,period=$('#filter-period').value;return records.filter(r=>{const day=dateKey(r.measured_at);return(!start||day>=start)&&(!end||day<=end)&&(period==='all'||r.period===period)})}
function row(r,history=false){const a=adviceFor(r);return `<div class="${history?'history-item':''}"><div class="reading-row"><span class="reading-mark" aria-hidden="true">${r.period==='Manhã'?'☀':r.period==='Tarde'?'◷':'☾'}</span><div class="reading-info"><strong>${escape(r.period)}</strong><small>${fmt(r.measured_at)}</small>${history?`<span class="status-chip ${a.level==='calm'?'':a.level}">${escape(a.label)}</span>`:''}</div><div class="reading-values"><strong>${r.systolic} / ${r.diastolic}</strong><small>mmHg${r.pulse?` · ${r.pulse} bpm`:''}</small></div>${history?`<div class="reading-actions"><button data-edit="${r.id}" aria-label="Editar medição de ${fmt(r.measured_at)}">Editar</button><button data-delete="${r.id}" aria-label="Excluir medição de ${fmt(r.measured_at)}">Excluir</button></div>`:''}</div>${history&&(r.symptoms?.length||r.notes)?`<div class="notes">${r.symptoms?.length?`<strong>Sintomas:</strong> ${escape(r.symptoms.join(', '))}<br>`:''}${escape(r.notes)}</div>`:''}</div>`}
function empty(title='Nenhuma medição ainda',copy='Registre sua pressão para começar seu histórico.'){return `<div class="empty"><strong>${title}</strong>${copy}</div>`}
function render(){
  const last=records[0],recent=subset(),today=records.filter(r=>dateKey(r.measured_at)===dateKey(new Date()));
  $('#last-sys').textContent=last?.systolic||'—';$('#last-dia').textContent=last?.diastolic||'—';$('#last-period').textContent=last?.period||'Sem registros';$('#last-time').textContent=last?fmt(last.measured_at):'—';$('#last-status').textContent=last?adviceFor(last).label:'Comece pelo seu primeiro registro';
  const days=new Set(today.map(r=>r.period));$('#day-count').textContent=`${days.size} de 3 períodos`;
  $('#day-periods').innerHTML=['Manhã','Tarde','Noite'].map((p,i)=>`<button class="period-card ${days.has(p)?'complete':''}" data-new-period="${p}"><span class="period-icon" aria-hidden="true">${['☀','◷','☾'][i]}</span><strong>${p}</strong><small>${days.has(p)?'✓ Registrado':'Registrar'}</small></button>`).join('');
  const avg=key=>Math.round(recent.reduce((sum,r)=>sum+r[key],0)/recent.length);$('#average').textContent=recent.length?`${avg('systolic')} / ${avg('diastolic')}`:'— / —';const pulses=recent.filter(r=>r.pulse!==null);$('#average-pulse').innerHTML=`${pulses.length?Math.round(pulses.reduce((s,r)=>s+r.pulse,0)/pulses.length):'—'} <small>bpm</small>`;$('#total').textContent=recent.length;$('#period-caption').textContent=range==='all'?'Todo o histórico':`Últimos ${range} dias`;
  $('#recent-list').innerHTML=records.length?records.slice(0,3).map(r=>row(r)).join(''):empty();
  if(last){const a=adviceFor(last);$('#guidance-title').textContent=a.title;$('#guidance-copy').textContent=`Na medição de ${fmt(last.measured_at)}: ${a.text}`}else{$('#guidance-title').textContent='Antes de medir';$('#guidance-copy').textContent='Sente-se em silêncio por 5 minutos, com as costas apoiadas, pés no chão e braço na altura do coração.'}
  const week=records.filter(r=>new Date(r.measured_at)>new Date(Date.now()-7*86400000)), elevated=week.filter(r=>r.systolic>=140||r.diastolic>=90);
  $('#insight-text').textContent=!last?'Seu primeiro registro é um pequeno gesto de cuidado. Vamos no seu ritmo.':adviceFor(last).emergency?'Os sintomas registrados na última medição exigem atendimento imediato se estiverem acontecendo agora. Não espere a próxima medição.':elevated.length>=2?`Nos últimos 7 dias, ${elevated.length} medições foram de 140 ou mais no número maior, ou 90 ou mais no menor. Leve esse padrão à equipe de saúde; o app não determina seu alvo de pressão.`:today.length?'Você já reservou um momento para se cuidar hoje. Os registros ajudam na consulta, qualquer que seja o número.':'Um novo dia, um cuidado de cada vez. Registre nos horários combinados com sua equipe de saúde.';
  $('#guidance-card')?.classList.toggle('attention',!!last&&adviceFor(last).level!=='calm');
  renderChart(recent);renderHistory();renderAccount();
}
function renderHistory(){const selected=filtered();$('#history-count').textContent=`${selected.length} ${selected.length===1?'registro':'registros'}`;$('#history-list').innerHTML=selected.length?selected.map(r=>row(r,true)).join(''):empty('Nenhum registro neste intervalo','Ajuste os filtros ou adicione uma medição.')}
function renderChart(data){if(!data.length){$('#chart').innerHTML=empty('Seu histórico começa aqui','As medições aparecerão neste gráfico após o primeiro registro.');return}const points=[...data].reverse(),w=Math.max(300,$('#chart').clientWidth),h=230,left=45,right=20,top=18,bottom=35,min=Math.max(0,Math.floor(Math.min(...points.map(r=>r.diastolic))/20)*20-20),max=Math.ceil(Math.max(...points.map(r=>r.systolic))/20)*20+20;const first=new Date(points[0].measured_at).getTime(),last=new Date(points.at(-1).measured_at).getTime();const x=r=>points.length===1?w/2:left+(new Date(r.measured_at).getTime()-first)/Math.max(1,last-first)*(w-left-right),y=v=>top+(max-v)/(max-min)*(h-top-bottom);let grid='';for(let i=0;i<=4;i++){const value=Math.round(min+(max-min)*i/4);grid+=`<line x1="${left}" x2="${w-right}" y1="${y(value)}" y2="${y(value)}" stroke="#e7eff1" stroke-dasharray="3 5"/><text x="0" y="${y(value)+4}" fill="#769098" font-size="12">${value}</text>`}const lines=['systolic','diastolic'].map((key,j)=>`<polyline points="${points.map(r=>`${x(r)},${y(r[key])}`).join(' ')}" fill="none" stroke="${j?'#e795ad':'#9165d6'}" stroke-width="${j?2:2.8}" stroke-linecap="round" stroke-linejoin="round"/>${points.map(r=>`<circle cx="${x(r)}" cy="${y(r[key])}" r="3.7" fill="${j?'#e795ad':'#9165d6'}" stroke="#fff" stroke-width="1.5"><title>${fmt(r.measured_at)} · ${r[key]} mmHg</title></circle>`).join('')}`).join('');const label=r=>new Date(r.measured_at).toLocaleDateString('pt-BR',{day:'2-digit',month:'2-digit'});$('#chart').innerHTML=`<svg role="img" aria-label="${points.length} medições de pressão arterial no período selecionado" viewBox="0 0 ${w} ${h}" preserveAspectRatio="none">${grid}${lines}<text x="${left}" y="${h-4}" fill="#769098" font-size="12">${label(points[0])}</text>${points.length>1?`<text x="${w-right}" y="${h-4}" text-anchor="end" fill="#769098" font-size="12">${label(points.at(-1))}</text>`:''}</svg>`}
function openReading(id=null,period=null){editId=id;const f=$('#reading-form');f.reset();$('#reading-error').textContent='';$('#reading-title').textContent=id?'Ajustar minha medição':'Como está sua pressão? 💜';const r=id?records.find(r=>r.id===id):null;if(r){for(const key of ['systolic','diastolic','pulse','period','notes'])f.elements[key].value=r[key]??'';f.elements.measured_at.value=localDatetime(new Date(r.measured_at));$$('[name="symptom"]').forEach(el=>el.checked=r.symptoms.includes(el.value))}else{f.elements.measured_at.value=localDatetime();f.elements.period.value=period||periodFor(new Date())}updateLiveAdvice();setView('inicio');$('#entry-card').scrollIntoView({behavior:'smooth',block:'start'});f.elements.systolic.focus({preventScroll:true})}
function formReading(){const f=$('#reading-form'),v=new FormData(f),date=new Date(v.get('measured_at'));return {systolic:Number(v.get('systolic')),diastolic:Number(v.get('diastolic')),pulse:v.get('pulse')?Number(v.get('pulse')):null,period:v.get('period'),measured_at:Number.isNaN(date.getTime())?'':date.toISOString(),symptoms:v.getAll('symptom'),notes:String(v.get('notes')||'').trim()}}
function updateLiveAdvice(){const r=formReading();const a=adviceFor(r);if(!a.emergency&&(!r.systolic||!r.diastolic)){$('#live-advice').className='advice';$('#live-advice').textContent='Digite o número maior e o menor, como aparecem no aparelho. As orientações aparecem aqui. Se tiver algum sintoma, marque abaixo.';return}const el=$('#live-advice');el.className=`advice ${a.level==='calm'?'':a.level}`;el.innerHTML=`<strong>${escape(a.title)}</strong><br>${escape(a.text)}${a.emergency?'<a href="tel:192">Ligar para o SAMU · 192</a>':''}`}
document.addEventListener('click',e=>{const nav=e.target.closest('[data-view]');if(nav)setView(nav.dataset.view);if(e.target.closest('.new-reading'))openReading();const p=e.target.closest('[data-new-period]');if(p)openReading(null,p.dataset.newPeriod);if(e.target.closest('.close-dialog'))e.target.closest('dialog').close();const edit=e.target.closest('[data-edit]');if(edit)openReading(edit.dataset.edit);const del=e.target.closest('[data-delete]');if(del){deleteId=del.dataset.delete;$('#delete-error').textContent='';$('#confirm-dialog').showModal()}if(e.target.closest('.report-action'))printReport()});
$('#sync-now').onclick=()=>loadRecords();
$('#reading-form').addEventListener('input',updateLiveAdvice);
$('#reading-form').onsubmit=async e=>{e.preventDefault();const button=$('#save-reading');$('#reading-error').textContent='';button.disabled=true;try{const r=formReading();validateReading(r);const body=editId?r:{...r,id:crypto.randomUUID()};const path=editId?`?id=${encodeURIComponent(editId)}`:'';const saved=await request(path,{method:editId?'PATCH':'POST',body,auth:true});if(!saved?.length)throw Error('Nenhum registro foi confirmado. Atualize e tente novamente.');++loadSequence;records=records.filter(x=>x.id!==saved[0].id);records.push(saved[0]);records.sort((a,b)=>new Date(b.measured_at)-new Date(a.measured_at));render();banner('');const advice=adviceFor(r);if(advice.level==='danger'||advice.emergency){$('#safety-title').textContent=advice.title;$('#safety-text').textContent=advice.text;$('#safety-call').hidden=!advice.emergency;$('#safety-dialog').showModal()}else toast(editId?'Medição atualizada.':'Guardado com carinho. Obrigada por cuidar de você! 💜');editId=null;$('#reading-form').reset();$('#reading-form').elements.measured_at.value=localDatetime();$('#reading-form').elements.period.value=periodFor(new Date());updateLiveAdvice()}catch(err){$('#reading-error').textContent=err.message}finally{button.disabled=false}};
$('#cancel-delete').onclick=()=>$('#confirm-dialog').close();$('#confirm-delete').onclick=async()=>{const b=$('#confirm-delete');b.disabled=true;try{const result=await request(`?id=${encodeURIComponent(deleteId)}`,{method:'DELETE',auth:true});if(!result?.length)throw Error('A exclusão não foi confirmada. Atualize e tente novamente.');++loadSequence;records=records.filter(r=>r.id!==deleteId);render();$('#confirm-dialog').close();toast('Registro excluído.')}catch(e){$('#delete-error').textContent=e.message}finally{b.disabled=false}};
$('#chart-range').onchange=e=>{range=e.target.value;render()};['filter-start','filter-end','filter-period'].forEach(id=>$('#'+id).onchange=renderHistory);$('#clear-filters').onclick=()=>{$('#filter-start').value='';$('#filter-end').value='';$('#filter-period').value='all';renderHistory()};
function csvCell(value){let s=String(value??'');if(/^[=+\-@\t\r]/.test(s))s="'"+s;return '"'+s.replace(/"/g,'""')+'"'}
$('#export-csv').onclick=()=>{const data=filtered();if(!data.length){toast('Nenhum registro no intervalo selecionado.');return}const rows=[['Data e hora','Período','Sistólica (mmHg)','Diastólica (mmHg)','Pulso (bpm)','Sintomas','Observações'],...data.map(r=>[fmt(r.measured_at),r.period,r.systolic,r.diastolic,r.pulse,r.symptoms.join(', '),r.notes])];const blob=new Blob(['\ufeff'+rows.map(r=>r.map(csvCell).join(';')).join('\r\n')],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`pulso-registros-${dateKey(new Date())}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
function printReport(){const data=filtered();if(!data.length){toast('Adicione uma medição antes de gerar o relatório.');return}setView('historico');$$('.report-header,.report-only').forEach(el=>el.remove());const header=document.createElement('div');header.className='report-header';header.innerHTML=`<h1>Pulso · Diário de pressão arterial</h1><p>Gerado em ${fmt(new Date())} · ${data.length} medições<br>Intervalo: ${$('#filter-start').value||'início do histórico'} a ${$('#filter-end').value||'hoje'} · Período: ${escape($('#filter-period').value==='all'?'todos':$('#filter-period').value)}</p>`;$('#view-historico').prepend(header);const foot=document.createElement('p');foot.className='report-only';foot.textContent='Valores informados pela usuária, não verificados pelo app. Este diário não estabelece diagnóstico e não substitui a avaliação médica. Os sintomas registrados se referem ao momento de cada medição. A média não descarta episódios de pressão muito elevada.';$('#view-historico').append(foot);window.print()}
$('#today-date').textContent=new Intl.DateTimeFormat('pt-BR',{weekday:'long',day:'numeric',month:'long'}).format(new Date());
async function prepareDiary(){
 try{
  const incoming=new URLSearchParams(location.hash.slice(1)).get('d');
  access=/^[A-Za-z0-9_-]{43}$/.test(incoming||'')?incoming:localStorage.getItem('pulso-access');
  if(!/^[A-Za-z0-9_-]{43}$/.test(access||'')){const bytes=crypto.getRandomValues(new Uint8Array(32));access=btoa(String.fromCharCode(...bytes)).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');}
  localStorage.setItem('pulso-access',access);
  if(incoming)history.replaceState(null,'',location.pathname+location.search+'#inicio');
  const response=await fetch(config.supabaseUrl+'/functions/v1/pulso-diary?start=1',{method:'POST',headers:{apikey:config.supabaseKey,'x-pulso-access':access},signal:AbortSignal.timeout(15000)});
  if(!response.ok)throw Error('Não consegui preparar o diário. Aguarde um pouco e atualize a página.');
 }catch(e){throw Error(e.message||'Este navegador precisa permitir armazenamento para lembrar seu diário.');}
}
setView(['inicio','historico','cuidados','conta'].includes(location.hash.slice(1))?location.hash.slice(1):'inicio');render();
$('#reading-form').elements.measured_at.value=localDatetime();$('#reading-form').elements.period.value=periodFor(new Date());updateLiveAdvice();
if(!configured)banner('A conexão com o banco ainda precisa ser configurada.');else{diaryReady=prepareDiary();diaryReady.then(()=>loadRecords()).catch(e=>banner(e.message));}
document.addEventListener('visibilitychange',()=>{if(!document.hidden&&access)loadRecords()});

const menu=$('#navigation-menu');
$('#open-menu').onclick=()=>{menu.showModal();$('#open-menu').setAttribute('aria-expanded','true');};
$('#close-menu').onclick=()=>menu.close();
menu.addEventListener('close',()=>$('#open-menu').setAttribute('aria-expanded','false'));
menu.addEventListener('click',e=>{if(e.target!==menu)return;const r=menu.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)menu.close();});

$('#make-pair-code').onclick=async()=>{const b=$('#make-pair-code');b.disabled=true;$('#pair-error').textContent='';try{const data=await request('?action=pair-code',{method:'POST'});$('#pair-code-output').hidden=false;$('#pair-code-output').textContent=`Seu código: ${data.code} · válido por 10 minutos. Digite exatamente assim no outro aparelho.`;}catch(e){$('#pair-error').textContent=e.message}finally{b.disabled=false}};
$('#pair-form').onsubmit=async e=>{e.preventDefault();if(records.length&&!confirm('Este aparelho passará a mostrar o diário do código. Os registros atuais continuam preservados no diário anterior. Continuar?'))return;const b=$('#join-pair');b.disabled=true;$('#pair-error').textContent='';try{await request('?action=pair-join',{method:'POST',body:{code:$('#pair-code-input').value.trim()}});++loadSequence;records=[];editId=null;render();await loadRecords();$('#pair-form').reset();toast('Aparelhos vinculados! Agora vocês usam o mesmo diário. 💜')}catch(e){$('#pair-error').textContent=e.message}finally{b.disabled=false}};
let syncBusy=false;
async function autoSync(){if(document.hidden||!access||syncBusy)return;syncBusy=true;try{await loadRecords(true)}finally{syncBusy=false}}
setInterval(autoSync,30000);window.addEventListener('focus',autoSync);window.addEventListener('online',autoSync);
window.addEventListener('storage',e=>{if(e.key==='pulso-access'&&e.newValue){access=e.newValue;++loadSequence;records=[];render();autoSync();}});
